"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Log = { _id: string; action: string; entityType: string; entityName?: string; category?: string; actor?: string; details?: string; createdAt?: string };
const date = (value?: string) => value ? new Date(value).toLocaleString("es-BO", { dateStyle: "medium", timeStyle: "short" }) : "Sin fecha";
export default function AdminHistoryClient({ initialLogs }: { initialLogs: Log[] }) {
  const [logs, setLogs] = useState(initialLogs); const [q, setQ] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [loading, setLoading] = useState(false);
  async function search() { setLoading(true); const p = new URLSearchParams(); if (q.trim()) p.set("q", q.trim()); if (from) p.set("from", from); if (to) p.set("to", to); try { const r = await fetch(`/api/historial?${p}`, { cache: "no-store" }); const d = await r.json(); if (r.ok) setLogs(Array.isArray(d.logs) ? d.logs : []); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setInterval(search, 20000); return () => window.clearInterval(timer); }, [q, from, to]);
  return <main className="min-h-screen overflow-x-hidden bg-[var(--bg)] px-4 py-6 text-[var(--text)] sm:px-8 sm:py-8 lg:px-12"><div className="mx-auto max-w-[1500px]"><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-4xl font-extrabold tracking-[-0.04em] sm:text-5xl">Historial</h1><p className="mt-2 text-sm font-semibold text-[var(--text-soft)] sm:text-base">Registro de cambios. Se actualiza automáticamente.</p></div><Link href="/admin" className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] px-5 py-3 text-sm font-extrabold">← Panel admin</Link></div><section className="rounded-[30px] border border-[var(--border)] bg-[var(--surface)] p-4 shadow-[0_10px_30px_var(--shadow)] sm:p-6"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto_auto]"><input value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => e.key === "Enter" && search()} placeholder="Buscar producto, categoría, pedido, cliente o acción..." className="h-12 rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] px-4 font-semibold outline-none focus:border-[var(--primary)]" /><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="h-12 rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] px-4 font-semibold" /><input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="h-12 rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] px-4 font-semibold" /><button type="button" onClick={search} className="h-12 rounded-2xl bg-[var(--primary)] px-5 text-sm font-extrabold text-white">{loading ? "Buscando..." : "Buscar"}</button></div></section><section className="mt-5 space-y-3">{logs.length === 0 ? <div className="rounded-[28px] border border-[var(--border)] bg-[var(--surface)] px-5 py-10 text-center font-semibold text-[var(--text-soft)]">No hay registros para estos filtros.</div> : logs.map((log) => <article key={log._id} className="rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-4 shadow-sm sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><span className="rounded-full bg-[var(--surface-soft)] px-3 py-1 text-xs font-extrabold text-[var(--primary)]">{log.entityType}</span><h2 className="mt-3 break-words text-lg font-extrabold">{log.action}{log.entityName ? ` · ${log.entityName}` : ""}</h2></div><time className="text-sm font-semibold text-[var(--text-muted)]">{date(log.createdAt)}</time></div>{log.details && <p className="mt-2 text-sm font-semibold text-[var(--text-soft)]">{log.details}</p>}<p className="mt-3 text-xs font-bold uppercase tracking-[0.12em] text-[var(--text-muted)]">Por: {log.actor || "Sistema"}{log.category ? ` · ${log.category}` : ""}</p></article>)}</section></div></main>;
}
